apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-gate
  namespace: api-services
  labels:
    app: webhook-gate
spec:
  selector:
    matchLabels:
      app: webhook-gate
  template:
    metadata:
      labels:
        app: webhook-gate
    spec:
      containers:
      - name: webhook-gate
        image: webhook-gate-image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-gate
  namespace: api-services
  labels:
    app: webhook-gate
spec:
  type: ClusterIP
  selector:
    app: webhook-gate
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
