apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: api-services
  annotations:
    configmap.reloader.stakater.com/reload: "envoy-config"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/stats/prometheus"
    prometheus.io/port: "9091"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy-tools:v1.33-latest
          args:
            - "/usr/local/bin/envoy"
            - "-c"
            - "/etc/envoy/minimal-envoy-config.yaml"
            - "--parent-shutdown-time-s"
            - "5"
            - "--drain-time-s"
            - "3"
            - "--drain-strategy"
            - "immediate"
            - "--component-log-level"
            - "config:debug,runtime:trace,file:debug,http:debug,http2:debug,grpc:debug,lua:debug,ext_authz:trace,router:trace"
          ports:
            - containerPort: 9901 # Admin interface
            - containerPort: 10000
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: api-services
spec:
  selector:
    app: envoy
  ports:
    - name: admin
      port: 9901
      targetPort: 9901
    - name: app
      port: 10000
      targetPort: 10000
